[features]
seeds = false
skip-lint = true

[programs.localnet]
anchor_project_template = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/khangnguyen/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.mocha.json ./tests/*.spec.ts --timeout 10000"
